# Generated by Django 6.0.7 on 2026-08-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('prioridad', models.CharField(choices=[('BAJA', 'baja'), ('MEDIA', 'media'), ('ALTA', 'alta')], default='MEDIA', max_length=5)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'completada'), ('PENDIENTE', 'pendiente'), ('EN_PROGRESO', 'en_progreso')], default='PENDIENTE', max_length=11)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestor_proyectos.proyecto')),
            ],
        ),
    ]
